"""cleans up models

Revision ID: 2f95e002318a
Revises: 8d4820381f5c
Create Date: 2024-05-01 13:19:17.738429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f95e002318a'
down_revision = '8d4820381f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.drop_constraint('uq_scheduled_days_day', type_='unique')
        batch_op.create_unique_constraint('unique_day_tutor', ['day', 'tutor_id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_scheduled', sa.Time(), nullable=True))
        batch_op.alter_column('date_scheduled',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_unique_constraint('unique_date_time_tutor', ['date_scheduled', 'time_scheduled', 'tutor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_date_time_tutor', type_='unique')
        batch_op.alter_column('date_scheduled',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('time_scheduled')

    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.drop_constraint('unique_day_tutor', type_='unique')
        batch_op.create_unique_constraint('uq_scheduled_days_day', ['day', 'tutor_id'])

    # ### end Alembic commands ###
