"""added contraint on course

Revision ID: 683569697162
Revises: 05e34e262498
Create Date: 2024-05-01 14:31:10.291395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683569697162'
down_revision = '05e34e262498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_course_tutor', ['name', 'tutor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('unique_course_tutor', type_='unique')

    # ### end Alembic commands ###
