"""changed DB type of Session day_scheduled to string and time_scheduled to int

Revision ID: 6f85292b4020
Revises: 683569697162
Create Date: 2024-05-01 16:24:22.795618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f85292b4020'
down_revision = '683569697162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_scheduled', sa.String(), nullable=True))
        batch_op.alter_column('time_scheduled',
               existing_type=sa.TIME(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint('unique_date_time_tutor', type_='unique')
        batch_op.create_unique_constraint('unique_date_time_tutor', ['day_scheduled', 'time_scheduled', 'tutor_id'])
        batch_op.drop_column('date_scheduled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_scheduled', sa.DATE(), nullable=True))
        batch_op.drop_constraint('unique_date_time_tutor', type_='unique')
        batch_op.create_unique_constraint('unique_date_time_tutor', ['date_scheduled', 'time_scheduled', 'tutor_id'])
        batch_op.alter_column('time_scheduled',
               existing_type=sa.Integer(),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.drop_column('day_scheduled')

    # ### end Alembic commands ###
