"""changed uniqueness

Revision ID: 80acdeffa25d
Revises: 9c291a29aa49
Create Date: 2024-06-13 10:35:21.845539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80acdeffa25d'
down_revision = '9c291a29aa49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutees', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tutees_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutees', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tutees_name', ['name'])

    # ### end Alembic commands ###
