"""adds day contraints

Revision ID: 8d4820381f5c
Revises: 9e9130177a6a
Create Date: 2024-05-01 12:01:41.370586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4820381f5c'
down_revision = '9e9130177a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['day', 'tutor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_days', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
