"""fixes broken db

Revision ID: 9c291a29aa49
Revises: e85a45cc912d
Create Date: 2024-05-03 14:39:53.337972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c291a29aa49'
down_revision = 'e85a45cc912d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('student_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutees')),
    sa.UniqueConstraint('name', name=op.f('uq_tutees_name'))
    )
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('certification_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutors')),
    sa.UniqueConstraint('name', name=op.f('uq_tutors_name'))
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], name=op.f('fk_courses_tutor_id_tutors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('name', 'tutor_id', name='unique_course_tutor')
    )
    op.create_table('scheduled_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], name=op.f('fk_scheduled_days_tutor_id_tutors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_days')),
    sa.UniqueConstraint('day', 'tutor_id', name='unique_day_tutor')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_scheduled', sa.String(), nullable=True),
    sa.Column('time_scheduled', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('tutee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutee_id'], ['tutees.id'], name=op.f('fk_sessions_tutee_id_tutees')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], name=op.f('fk_sessions_tutor_id_tutors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('day_scheduled', 'time_scheduled', 'tutor_id', name='unique_date_time_tutor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('scheduled_days')
    op.drop_table('courses')
    op.drop_table('tutors')
    op.drop_table('tutees')
    # ### end Alembic commands ###
