"""adds app.py imports and cleans up table names

Revision ID: 9e9130177a6a
Revises: 
Create Date: 2024-05-01 11:50:18.031585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9130177a6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('student_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('certification_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], name=op.f('fk_courses_tutor_id_tutors')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], name=op.f('fk_scheduled_days_tutor_id_tutors')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_scheduled', sa.DateTime(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('tutee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutee_id'], ['tutees.id'], name=op.f('fk_sessions_tutee_id_tutees')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], name=op.f('fk_sessions_tutor_id_tutors')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('scheduled_days')
    op.drop_table('courses')
    op.drop_table('tutors')
    op.drop_table('tutees')
    # ### end Alembic commands ###
